# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "gh-actions-eks-ecosystem"
    key            = "IaC/terraform.tfstate"
    region         = "us-east-2"
    encrypt        = true
    dynamodb_table = "state-table"
  }
}
