# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}
provider "helm" {
  kubernetes {
    host                   = module.eks-cluster.eks_cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks-cluster.eks_cluster_certificate_authority_data.0.data)
    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      args        = ["eks", "get-token", "--cluster-name", module.eks-cluster.eks_cluster_name]
      command     = "aws"
    }
  }
}
