name: Update Terraform Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write


jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: TF-DOCS

      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Update Terraform Docs
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ./IaC

      - name: "Import GPG key"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit changes to the repository
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Commiting Updates to Terraform Documentation. 
          commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
          commit_user_name: ${{ steps.import-gpg.outputs.name }}
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
